 <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.9.1.js"></script>
  <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>  
<script>
  $(function() {
    $( "#writeDatePicker" ).datepicker();
    $( "#publDatePicker" ).datepicker();
  });
  </script>
                                 <div  id="edit-service">
                                    <div class="container">

 <?= $this->form;?>
                                        <div class="clearfix"></div>

                                    </div>
                                </div></br>     
        
     
        

         <script type="text/javascript">
$(document).ready(function(){
  $('#search').removeClass('active');                
   $('#shelfs').removeClass('active');
   //add
   $('#all_books').addClass('active');
});
</script>        