
                <section id="content">
                 
                    <div class="page-splash" id="serviceList" style="height : 299px;">
                        <div class="inner" >
                    <div class="container">
                                <div class="sixteen columns">
                                    <h2 class="title">
                                        Список книг
                                    </h2>
                                  
                                </div>
                                <div class="clear"></div>
                            </div>
                        </div>
                    </div>
                   
                    <div class="container">
                        <div class="row-indent">

                            <div style="margin-top: -100px" id="category-list">   
                       
                                <div class="container">
                                    <div class="sixteen columns marg-bott-cont">
                                        <div class="portfolio-controls">
                                  
                                                <a href="<?= $this->url(array('controller'=>'index', 'action'=>'add-service'))?>" class="button1">Добавить книгу</a>
                                          
                                            <div class="view-mode">
                                                <a href="#" class="view-mode-grid"></a>
                                                <a href="#" class="view-mode-list active"></a>
                                            </div>
                                            <div class="clearfix"></div>
                                        </div>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <div class="portfolio-container">
                                    <div class="container">
                                      
     
       
    <?php   foreach($this->paginator as $service){ ?>
            <div class="one-third column photography element" data-category="photography">
                                    <div class="portfolio-item">
                                        <a href="<?= $this->baseUrl() ?>/images/old-book.jpg" class="portfolio-link"><img src="<?= $this->baseUrl() ?>/images/old-book.jpg" alt=""/><div class="hoverDir"><span></span></div></a>
                                        <div class="inner">
                                            <div><?= $service['author'] ?></div>
                                            <div><a href="<?= $this->url(array('controller' => 'index', 'action' => 'description')).'?id='.$service['id'] ?>"><?= $service['title'] ?></a></div>
                                            
                                           
                                            <div class="car-slide-row">
                                                
                                                <a href="<?= $this->url(array('controller' => 'index', 'action' => 'edit-service')) ?>?id=<?= $service['id'] ?>" class="button1">Редактировать</a>
                                            </div>
                                            <div class="car-slide-row">
                                                
                                                <a href="<?= $this->url(array('controller' => 'index', 'action' => 'remove-service')) ?>?id=<?= $service['id'] ?>" class="button1">Удалить</a>
                                            </div>
                                        </div>
                                    </div>
                                </div> 

     <?php   } ?>
       
          
                                        <div class="clearfix"></div>

                                    </div>
                                </div>
                            </div></br>
<?= $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml') ?>
                            <div class="clearfix"></div>
                        </div>
                    </div>

                </section>      
        

        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-2.0.0.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery-migrate-1.1.1.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.easing.1.3.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/raphael-min.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.validationEngine-en.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.form.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.hoverdir.js"></script>
        <script type="text/javascript" src="<?= $this->baseUrl() ?>/desktop/js/jquery.selectik.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.isotope.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/touchTouch.jquery.js"></script>
        <script src="http://twitterjs.googlecode.com/svn/trunk/src/twitter.min.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.carouFredSel-6.2.1.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/tabs.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/toggles.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/boxes.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/settings-panel.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/jquery.cookie.js"></script>
        <script src="<?= $this->baseUrl() ?>/desktop/js/script.js"></script>
        <script>
            $(document).ready(function(){
                   //remove class
   $('#search').removeClass('active');                
   $('#shelfs').removeClass('active');
   //add
   $('#all_books').addClass('active');

                
                //set as default view of the list as a list
                $('.portfolio-container .column').addClass('list-view');
                
                "use strict";
                $('.header_menu a').each(function(i){
                    var link = $(this).attr('href');
                    var text;
                    if($(this).parents('ul.sub-menu').length!=0){
                        text = '--'+$(this).text();
                    } else {
                        text = $(this).text();
                    }
                    if(window.location.href.indexOf(link)!=-1){
                        $('#mobile_menu').append('<option value="'+link+'" selected="selected">'+text+'</option>');
                    } else{
                        $('#mobile_menu').append('<option value="'+link+'">'+text+'</option>'); 
                    }
                });
                $('#mobile_menu').live('change', function(){
                    if($(this).val()!=''){
                        window.location = $(this).val();
                    }
                });
                $(' .portfolio-link ').each( function() { 
                    $(this).hoverdir({
                        hoverDelay : 75
                    });
                });
                
                $('.slide-container>a, .portfolio-link').touchTouch();
                if(navigator.platform.indexOf("iPhone") != -1 || navigator.platform.indexOf("iPad") != -1 || navigator.platform.indexOf("iPod") != -1){
                    jQuery('#filter').addClass('iphone_select');
                }
                $('#filter').selectik({maxItems: 8},
                {
                    _generateHtml: function(){
                        this.$collection = this.$cselect.children();
                        var html = '';
                        for (var i = 0; i < this.$collection.length; i++){
                            var $this = $(this.$collection[i]);
                            var textOption = $this[0].text;
                            var valueOption = $this[0].value;
                            html += '<li class="'+ ($this.attr('disabled') === 'disabled' ? 'disabled' : '') +' new" data-value="'+valueOption+'">'+textOption+'</li>';
                        };
                        return html;
                    }
                }
            ); 
            
                $('.view-mode a').click(function(e){
                    e.preventDefault();
                    $('.view-mode a').addClass('active');
                    $(this).removeClass('active');
                    if($(this).hasClass('view-mode-list')){
                        console.log('add');
                        $('.portfolio-container .column').removeClass('list-view');
                    } else {
                        console.log('remove');
                        $('.portfolio-container .column').addClass('list-view');
                    }
                    $('.portfolio-container').isotope( 'reLayout');

                });
            });

            
            function showPageSplash(){
                $('.page-splash').stop().animate({'height':'299px'},1500, 'easeOutBounce', portfolioUp);
            }
            function portfolioUp(){
                $('.portfolio-page-container').addClass('portfolio-page-up');
            }
        </script>
        
